version: '3.7'

services:
  contradb:
    build: ./ContraDB
    volumes:
      - /dock/contradomain/contradb:/var/lib/postgresql/data:z
    networks:
      - contranet
    hostname: contradb

  contralog:
    build: ./ContraLog
    volumes:
      - /dock/contradomain/contralog:/var/lib/clickhouse:z
    networks:
      - contranet
    hostname: contralog

  contracore:
    build: ./ContraCore
    networks:
      - contranet
    depends_on:
      - contradb
      - contralog
    working_dir: "/opt/"
    command: ["/opt/wait-for-it.sh", "contradb:5432", "--", "/opt/coredns"]
    ports:
      - "530:53/tcp"
      - "530:53/udp"
      - "64417:64417/tcp"
    hostname: contracore

  contraweb:
    build: ./ContraWeb
    networks:
      - contranet
    depends_on:
      - contradb
      - contracore
    command: ["dotnet", "./Web.dll"]
    ports:
      - "80:80/tcp"
    hostname: contraweb
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80

networks:
  contranet:
